sonata_admin:
    title: 'Sonata Admin'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]

services:
    admin.match:
        class: App\Admin\Match\MatchAdmin
        arguments: [~, App\Entity\Match\Match, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Matches, group: 'Matches'}
        public: true

    admin.terrain:
        class: App\Admin\Types\TerrainAdmin
        arguments: [~, App\Entity\Map\Terrain, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'Terrain Types', group: 'Types'}
        public: true

    admin.building:
        class: App\Admin\Types\BuildingAdmin
        arguments: [~, App\Entity\Match\Building, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'Building Types', group: 'Types'}
        public: true
