App\Entity\Map\Terrain:

    type: entity
    table: terrain

    id: { id: { type: integer, options: { unsigned: true } , generator: { strategy: auto } } }

    fields:
        name: { type: string }

        base_tide_cost:
            type: integer
            nullable: false
            options:
                unsigned: true

        base_supply_output:
            type: integer
            options:
                unsigned: true
