App\Entity\Match\Building:

    type: entity
    table: building

    id: { id: { type: integer, options: { unsigned: true } , generator: { strategy: auto } } }

    fields:
        name: { type: string }
