App\Entity\Match\Army:

    type: entity
    table: army

    id: { id: { type: integer, options: { unsigned: true } , generator: { strategy: auto } } }

    fields:
        size: { type: integer, options: { unsigned: true, default: 0 } }

    manyToOne:
        empire: { targetEntity: App\Entity\Match\Empire }
        territory_state: { targetEntity: App\Entity\Match\TerritoryState, inversedBy: armies }
