App\Entity\User\User:

    type: entity
    table: '`user`'

    id: { id: { type: integer, options: { unsigned: true } , generator: { strategy: auto } } }

    fields:
        username: { type: string(24) }
        email: { type: string }
        password: { type: string(4096) }
        date_registered: { type: datetime }
        api_key: { type: string, unique: true }
        validated: { type: boolean, options: {default: false}}

    lifecycleCallbacks:
        prePersist: [setDateRegisteredToNow]
